version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    target-branch: development
